### PR TITLE
ENH start moving stuff to conda

### PR DESCRIPTION
**Pull request by beckermr**
This PR starts to move the dockerfile to conda.

### CODE REVIEW

**Comment by beckermr** [comment]
This PR moves the stable-looking stuff. Things that appear to be in flux I will wait on. 

ready for review and testing @joezuntz!

**Comment by joezuntz** [comment]
I tested this in the dev image and got a solve error: https://github.com/LSSTDESC/txpipe-docker/actions/runs/4608330621

**Comment by joezuntz** [comment]
I didn't merge directly at first because of other changes to the two docker files that were in conflict. But that didn't work so I just tested yours outright. If there's a fix then we will have to do some more fiddling and go back to the previous version and then merge properly.

**Comment by beckermr** [comment]
It looks like I missed a package that needed to be added to conda-forge. I will bump you when it is ready to try again.

**Comment by beckermr** [comment]
@joezuntz This works now. Shall I rebase?

**Comment by joezuntz** [comment]
Go for it, yep

**Comment by beckermr** [comment]
Where are the conflicts? I didn't get any.

**Comment by joezuntz** [comment]
Oh yeah, forgot that I'd copied in your changes to test them. So can just merge in your last fix now.  Will do that and then run the dev action. Then once I've tested that everything works on NERSC I can copy the dev Dockerfile into the primary one.

**Pull request merged**
